/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ScholorshipAccount;

import DBoperations.DBoperationWithFinal;
import DBoperations.DBoperations;
import Member.MemberDetails;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Thilina
 */
public class NewScholorship extends javax.swing.JFrame {

    DBoperations DBoperation = new DBoperations();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form NewScholorship
     */
    public NewScholorship() {
        initComponents();
         btnValidate.setEnabled(false);
    }
    MemberDetails member;
    Float Amount;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtEmpNo = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSchool = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox();
        cbSholorshipType = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmpFirsttName = new javax.swing.JTextField();
        txtEmpLastName = new javax.swing.JTextField();
        txtEmpPrison = new javax.swing.JTextField();
        txtNICNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnValidate = new javax.swing.JButton();
        cbDOB = new org.freixas.jcalendar.JCalendarCombo();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Scholorship");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Scholorship Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Scholorship Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Emp No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DOB");

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        txtEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNoActionPerformed(evt);
            }
        });
        txtEmpNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmpNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpNoKeyTyped(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Amount");

        txtAmount.setEditable(false);
        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAmount.setText("10000.00");
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Last Name");

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("School");

        txtSchool.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolActionPerformed(evt);
            }
        });
        txtSchool.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSchoolKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gender");

        cbGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });

        cbSholorshipType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE_V_SCHOLORSHIP", "GCE_A/L _SCHOLORSHIP" }));
        cbSholorshipType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSholorshipTypeMouseClicked(evt);
            }
        });
        cbSholorshipType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSholorshipTypeItemStateChanged(evt);
            }
        });
        cbSholorshipType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSholorshipTypeActionPerformed(evt);
            }
        });
        cbSholorshipType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbSholorshipTypePropertyChange(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Emp First Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Emp Last Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Prison");

        txtEmpFirsttName.setEditable(false);
        txtEmpFirsttName.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpFirsttName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpFirsttName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpFirsttNameActionPerformed(evt);
            }
        });

        txtEmpLastName.setEditable(false);
        txtEmpLastName.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpLastNameActionPerformed(evt);
            }
        });

        txtEmpPrison.setEditable(false);
        txtEmpPrison.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpPrison.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpPrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpPrisonActionPerformed(evt);
            }
        });

        txtNICNo.setEditable(false);
        txtNICNo.setBackground(new java.awt.Color(255, 255, 255));
        txtNICNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNICNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNICNoMouseExited(evt);
            }
        });
        txtNICNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICNoActionPerformed(evt);
            }
        });
        txtNICNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNICNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNICNoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("NIC No:");

        btnValidate.setText("Validate");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        cbDOB.setDate(new java.util.Date());
        cbDOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(cbSholorshipType, 0, 223, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGender, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSchool, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNICNo)
                            .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnValidate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmpFirsttName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmpLastName)
                            .addComponent(txtEmpPrison))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmpFirsttName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmpPrison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNICNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSholorshipType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNoActionPerformed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        

    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        ScholorshipDetails ed = new ScholorshipDetails();

        try {
            System.out.println(txtFirstName.getText());
            ed.setFirstName(txtFirstName.getText());
            ed.setLastName(txtLastName.getText());
            ed.setDob(dateFormat.format(cbDOB.getDate()));
            ed.setSchool(txtSchool.getText());
            ed.setGender((String) cbGender.getSelectedItem());
            ed.setEmpNo(Integer.parseInt(txtEmpNo.getText()));
            //ed.setEmpLastName(txtEmpFirsttName.getText());
            ed.setScholorshipType((String) cbSholorshipType.getSelectedItem());
            ed.setAmount((float)Amount);
            ed.setOwnerID(member.getOwnerID());
            ed.setAccountNo(member.getAccountNo());
            


            boolean result = DBoperation.newScholorship(ed);
            // boolean resultOwner = DBoperation.addOwnerTransfer(ownershipDetails);
            if (result) {
                JOptionPane.showMessageDialog(this, "Waiting For Authorization");
                //clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Error occurs while inserting");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Member details are not valid");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderActionPerformed

    private void txtSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolActionPerformed

    private void cbSholorshipTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSholorshipTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSholorshipTypeActionPerformed

    private void txtEmpFirsttNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpFirsttNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpFirsttNameActionPerformed

    private void txtEmpLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpLastNameActionPerformed

    private void txtEmpPrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpPrisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpPrisonActionPerformed

    private void txtNICNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNICNoMouseExited
    }//GEN-LAST:event_txtNICNoMouseExited

    private void txtNICNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICNoKeyTyped

    private void txtNICNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICNoKeyReleased
    }//GEN-LAST:event_txtNICNoKeyReleased

    private void txtNICNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICNoKeyPressed
    }//GEN-LAST:event_txtNICNoKeyPressed

    private void txtNICNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICNoActionPerformed
    DBoperationWithFinal DBWithFinal = new DBoperationWithFinal();
    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        
        member = DBWithFinal.getMemberByID(Integer.parseInt(txtEmpNo.getText()));
        if (member == null) {
            JOptionPane.showMessageDialog(this, "Member No is not valid");
    

        } else {

            txtNICNo.setText(member.getNicNo());
            txtEmpFirsttName.setText(member.getFirstName());
            txtEmpLastName.setText(member.getLastName());
            txtEmpPrison.setText(member.getPrison());


        }
        

    }//GEN-LAST:event_btnValidateActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void cbSholorshipTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbSholorshipTypePropertyChange
         
    }//GEN-LAST:event_cbSholorshipTypePropertyChange

    private void cbSholorshipTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSholorshipTypeMouseClicked
          
    }//GEN-LAST:event_cbSholorshipTypeMouseClicked

    private void cbSholorshipTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSholorshipTypeItemStateChanged
        // TODO add your handling code here:
 
        if (cbSholorshipType.getSelectedItem().equals("GRADE_V_SCHOLORSHIP")){
              Amount = 10000.f;
         
        }
            else{
            Amount = 25000.f;
            
                    }
         txtAmount.setText(String.valueOf(Amount));
    }//GEN-LAST:event_cbSholorshipTypeItemStateChanged

    private void txtEmpNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNoKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        String in =txtEmpNo.getText();
        if(!Character.isDigit(c)){
           evt.consume();
           Toolkit tk = Toolkit.getDefaultToolkit();
             tk.beep();
            
    }
    }//GEN-LAST:event_txtEmpNoKeyTyped

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        // TODO add your handling code here:
           char c=evt.getKeyChar();
        String in = txtFirstName.getText();
        if(c!=' '){
        if(!Character.isLetter(c)|| Character.isDigit(c)){
           evt.consume();
           Toolkit tk = Toolkit.getDefaultToolkit();
             tk.beep();}}
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        // TODO add your handling code here:
             char c=evt.getKeyChar();
        String in = txtLastName.getText();
        if(c!=' '){
        if(!Character.isLetter(c)|| Character.isDigit(c)){
           evt.consume();
           Toolkit tk = Toolkit.getDefaultToolkit();
             tk.beep();}}
        
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtSchoolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSchoolKeyTyped
        // TODO add your handling code here:
             char c=evt.getKeyChar();
        String in = txtSchool.getText();
        if(c!=' '){
        if(!Character.isLetter(c)|| Character.isDigit(c)){
           evt.consume();
           Toolkit tk = Toolkit.getDefaultToolkit();
             tk.beep();}}
    }//GEN-LAST:event_txtSchoolKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtAmountKeyTyped

    private void txtEmpNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNoKeyReleased
        // TODO add your handling code here:
         if(!"".equals(txtEmpNo.getText()))
        {
            btnValidate.setEnabled(true);
        }
        else{
  
            btnValidate.setEnabled(false);
        }
      
    }//GEN-LAST:event_txtEmpNoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewScholorship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewScholorship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewScholorship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewScholorship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewScholorship().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnValidate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private org.freixas.jcalendar.JCalendarCombo cbDOB;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbSholorshipType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtEmpFirsttName;
    private javax.swing.JTextField txtEmpLastName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtEmpPrison;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNICNo;
    private javax.swing.JTextField txtSchool;
    // End of variables declaration//GEN-END:variables

    public boolean isAlpha(String name) {
        char[] chars = name.toCharArray();

        for (char c : chars) {
            if (!Character.isLetter(c)) {
                return false;
            }
        }

        return true;
    }
}
