/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DeathGrant;

import DBoperations.DBoperationWithFinal;
import DBoperations.DBoperations;
import Table.DeathLoan;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Thilina
 */

public class DeathGrantLoan extends javax.swing.JFrame {

    ArrayList<DeathGrantDetails> deathgrantloan;
    DBoperations DBoperation = new DBoperations();
    DBoperationWithFinal DBWithFinal = new DBoperationWithFinal();
    
    
    public DeathGrantLoan() {
        initComponents();
        loadDeathGrantLoan();
    }
    //
private void loadDeathGrantLoan(){
    
        deathgrantloan = DBWithFinal.getDeathGrantLoanByPrison("Ambepussa");
        DeathLoan deathgrantloanList = new DeathLoan(deathgrantloan);
        tblDeathGrantLoan.setModel(deathgrantloanList);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel22 = new javax.swing.JPanel();
        btnNewDeathGrant2 = new javax.swing.JButton();
        btnDeleteDeathGrant2 = new javax.swing.JButton();
        btnViewDeathGrant2 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        cbPrison = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        btnSearch6 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeathGrantLoan = new javax.swing.JTable();
        btnUpdateDeathGrant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Death Grant Loan");
        setLocationByPlatform(true);

        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        btnNewDeathGrant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewDeathGrant2.setText("New Death Grant Loan");
        btnNewDeathGrant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDeathGrant2ActionPerformed(evt);
            }
        });

        btnDeleteDeathGrant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteDeathGrant2.setText("Delete Death Grant Loan");
        btnDeleteDeathGrant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDeathGrant2ActionPerformed(evt);
            }
        });

        btnViewDeathGrant2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewDeathGrant2.setText("View Details Loan");
        btnViewDeathGrant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeathGrant2ActionPerformed(evt);
            }
        });

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cbPrison.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPrison.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));
        cbPrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrisonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Prison");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Emp No");

        txtEmpNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpNoKeyTyped(evt);
            }
        });

        btnSearch6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch6.setText("Search");
        btnSearch6.setToolTipText("Click here to search member");
        btnSearch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cbPrison, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch6)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSearch6))
        );

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblDeathGrantLoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDeathGrantLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DeathGrant Loan No", "DeathGrant No", "Last Name", "Emp NIC", "Prison", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDeathGrantLoan);

        jScrollPane5.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnUpdateDeathGrant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateDeathGrant.setText("Update Death Grant Loan");
        btnUpdateDeathGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeathGrantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(btnNewDeathGrant2)
                        .addGap(44, 44, 44)
                        .addComponent(btnUpdateDeathGrant)
                        .addGap(44, 44, 44)
                        .addComponent(btnViewDeathGrant2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnDeleteDeathGrant2)
                        .addContainerGap(280, Short.MAX_VALUE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewDeathGrant2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateDeathGrant))
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteDeathGrant2)
                        .addComponent(btnViewDeathGrant2)))
                .addGap(45, 45, 45)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewDeathGrant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDeathGrant2ActionPerformed
        NewDeathGrantLoan newDeathGrantloan = new NewDeathGrantLoan();
        newDeathGrantloan  .setVisible(true);
        newDeathGrantloan  .setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btnNewDeathGrant2ActionPerformed

    private void btnDeleteDeathGrant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeathGrant2ActionPerformed
    DeleteDeathLoan delete = new DeleteDeathLoan();
        try {
            delete.setdeathgrantFields(deathgrantloan.get(tblDeathGrantLoan.getSelectedRow()));
            delete.setVisible(true);
            delete.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
                
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        
    }                                     
    }//GEN-LAST:event_btnDeleteDeathGrant2ActionPerformed

    private void btnViewDeathGrant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeathGrant2ActionPerformed
        ViewDeathGrantlLoan view = new ViewDeathGrantlLoan();
        try {
            view.setFields(deathgrantloan.get(tblDeathGrantLoan.getSelectedRow()));
            view.setVisible(true);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnViewDeathGrant2ActionPerformed

    private void cbPrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrisonActionPerformed

    private void btnSearch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch6ActionPerformed
        String EmpNO = txtEmpNo.getText();
        String prison = (String) cbPrison.getSelectedItem();

        if (EmpNO.equals("")) {
            deathgrantloan = DBWithFinal.getDeathGrantLoanByPrison(prison);
            DeathLoan deathgrantList = new DeathLoan(deathgrantloan);
            tblDeathGrantLoan.setModel(deathgrantList);
        } else {
            deathgrantloan = DBWithFinal.getDeathGrantLoanEmpNoAndByPrison(EmpNO, prison);
            DeathLoan deathgrantList = new DeathLoan(deathgrantloan);
            tblDeathGrantLoan.setModel(deathgrantList);}
    }//GEN-LAST:event_btnSearch6ActionPerformed

    private void btnUpdateDeathGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeathGrantActionPerformed
        UpdateDeathGrantLoan updatedeathGrantLoan = new UpdateDeathGrantLoan();

        try {
            updatedeathGrantLoan .setFields(deathgrantloan.get(tblDeathGrantLoan.getSelectedRow()));
            updatedeathGrantLoan .setVisible(true);
            updatedeathGrantLoan .setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a Death Grant !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnUpdateDeathGrantActionPerformed

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
        //loadDeathGrantLoan();
    }//GEN-LAST:event_jPanel22MouseClicked

    private void txtEmpNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNoKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        String in =txtEmpNo.getText();
        if(!Character.isDigit(c)){
           evt.consume();
           Toolkit tk = Toolkit.getDefaultToolkit();
             tk.beep();
            
    }
    }//GEN-LAST:event_txtEmpNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeathGrantLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeathGrantLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeathGrantLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeathGrantLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeathGrantLoan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDeathGrant2;
    private javax.swing.JButton btnNewDeathGrant2;
    private javax.swing.JButton btnSearch6;
    private javax.swing.JButton btnUpdateDeathGrant;
    private javax.swing.JButton btnViewDeathGrant2;
    private javax.swing.JComboBox cbPrison;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblDeathGrantLoan;
    private javax.swing.JTextField txtEmpNo;
    // End of variables declaration//GEN-END:variables
}
