/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import DBoperations.DBoperationWithFinal;
import Member.ViewMemberDetails;
import Member.MemberDetails;
import DBoperations.DBoperations;
import DeathGrant.DeathGrantDetails;
import DeathGrant.ViewDeathGrant;
import LoanAccount.LoanAccountDetails;
import LoanAccount.ViewLoanAccount;
import Table.Member;
import fundadministrationsystem.ChangePassword;
import fundadministrationsystem.UserDetails;
import fundadministrationsystem.ViewUser;
import SavingAccount.SavingsAccountDetails;
import SavingAccount.ViewAccountDetails;
import ScholorshipAccount.ScholorshipDetails;
import ScholorshipAccount.ViewScholorship;
import Table.DeathGrant;
import Table.LoanAccount;
import Table.SavingsAccount;
import Table.Scholorship;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author GWSC GINTOTA
 */
public class Auditor extends javax.swing.JFrame {

    /**
     * Creates new form Auditor
     */
    ArrayList<MemberDetails> members;
    ArrayList<LoanAccountDetails> loanAccount;
    ArrayList<ScholorshipDetails> scholorship;
    ArrayList<SavingsAccountDetails> savingsAccount;
    ArrayList<DeathGrantDetails> deathgrant;
    DBoperations DBoperation = new DBoperations();
    DBoperationWithFinal DBWithFinal = new DBoperationWithFinal();
    public static String currentUserID;

    public Auditor(String userID) {
        initComponents();
        currentUserID = userID;

        loadAccount();
        loadScholorship();
        loadAccount();
        loadDeathGrant();
    }

    private void loadMember() {
        members = DBWithFinal.getMemberByPrison("Ambepussa");
        Member memberList = new Member(members);
        tblMember.setModel(memberList);

    }

    private void loadLoanAccount() {
        loanAccount = DBWithFinal.getLoanAccountByPrison("Badulla");
        LoanAccount loanList = new LoanAccount(loanAccount);
        tblLoanAccount.setModel(loanList);

    }

    private void loadAccount() {
        savingsAccount = DBWithFinal.getAccountByPrison("Ambepussa");
        SavingsAccount accountList = new SavingsAccount(savingsAccount);
        tblSavingAccount.setModel(accountList);

    }

    private void loadScholorship() {
        scholorship = DBWithFinal.getScholorshipByPrison("Ambepussa");
        Scholorship scholorshipList = new Scholorship(scholorship);
        tblScholorship.setModel(scholorshipList);

    }

    private void loadDeathGrant() {
        deathgrant = DBWithFinal.getDeathGrantByPrison("Ambepussa");
        DeathGrant deathgrantList = new DeathGrant(deathgrant);
        tblDeathGrant.setModel(deathgrantList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSavingAccount = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAccountUserName = new javax.swing.JTextField();
        txtAccountNIC = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        cbAccountPrison = new javax.swing.JComboBox();
        cbAccountNIC = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        btnViewAccount = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAccountUserName1 = new javax.swing.JTextField();
        txtAccountNIC1 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        cbAccountPrison1 = new javax.swing.JComboBox();
        cbAccountNIC1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtApplicationNo = new javax.swing.JTextField();
        btnNewLoanAccount1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLoanAccount = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        btnViewDeathGrant = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        cbDeathGrantPrison = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEmpNo2 = new javax.swing.JTextField();
        btnSearch4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDeathGrant = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnViewDetails = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        cbPrison1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEmpNo1 = new javax.swing.JTextField();
        btnSearch3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblScholorship = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnViewMember = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtEmpNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbPrison = new javax.swing.JComboBox();
        cbNIC = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        menuProfileSettings = new javax.swing.JMenu();
        menuViewDetails = new javax.swing.JMenuItem();
        menuChangePassword = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prison Department Mutual Provident Fund");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("You Logged as : ");

        txtUserName.setEditable(false);
        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtUserName.setToolTipText("Current User");
        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setTabLayoutPolicy(1);
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(1171, 1171));

        jScrollPane4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 402));

        tblSavingAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblSavingAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4l", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSavingAccount.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblSavingAccount);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search Savings Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Last Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Prison");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("NIC");

        txtAccountUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountUserNameKeyTyped(evt);
            }
        });

        txtAccountNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountNIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAccountNICMouseExited(evt);
            }
        });
        txtAccountNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccountNICKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountNICKeyTyped(evt);
            }
        });

        btnSearch1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch1.setText("Search");
        btnSearch1.setToolTipText("Click here to search member");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        cbAccountPrison.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAccountPrison.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));

        cbAccountNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAccountNIC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "X" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Account No");

        txtAccountNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbAccountPrison, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAccountUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAccountNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbAccountNIC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(btnSearch1)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(759, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAccountPrison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAccountNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnSearch1)
                .addContainerGap())
        );

        btnViewAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewAccount.setText("View Account");
        btnViewAccount.setToolTipText("Click to view Account details and transactions");
        btnViewAccount.setMaximumSize(new java.awt.Dimension(123, 23));
        btnViewAccount.setMinimumSize(new java.awt.Dimension(123, 23));
        btnViewAccount.setPreferredSize(new java.awt.Dimension(123, 23));
        btnViewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAccountMouseClicked(evt);
            }
        });
        btnViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnViewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Savings Account", jPanel7);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search Savings Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel15.setPreferredSize(new java.awt.Dimension(900, 248));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Last Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Prison");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("NIC");

        txtAccountUserName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountUserName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountUserName1KeyTyped(evt);
            }
        });

        txtAccountNIC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccountNIC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAccountNIC1MouseExited(evt);
            }
        });
        txtAccountNIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNIC1ActionPerformed(evt);
            }
        });
        txtAccountNIC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccountNIC1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccountNIC1KeyTyped(evt);
            }
        });

        btnSearch2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch2.setText("Search");
        btnSearch2.setToolTipText("Click here to search member");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        cbAccountPrison1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAccountPrison1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));

        cbAccountNIC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAccountNIC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "X" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Application No");

        txtApplicationNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApplicationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApplicationNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbAccountPrison1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAccountUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAccountNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbAccountNIC1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(btnSearch2)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApplicationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAccountPrison1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApplicationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAccountNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnNewLoanAccount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewLoanAccount1.setText("View Loan Account");
        btnNewLoanAccount1.setToolTipText("Click to update account");
        btnNewLoanAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewLoanAccount1MouseClicked(evt);
            }
        });
        btnNewLoanAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewLoanAccount1ActionPerformed(evt);
            }
        });

        jScrollPane6.setPreferredSize(new java.awt.Dimension(700, 402));

        tblLoanAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblLoanAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoanAccount.setMaximumSize(new java.awt.Dimension(32767, 32767));
        tblLoanAccount.setPreferredSize(new java.awt.Dimension(600, 64));
        jScrollPane6.setViewportView(tblLoanAccount);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(btnNewLoanAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnNewLoanAccount1)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Loan Account", jPanel8);

        btnViewDeathGrant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewDeathGrant.setText("View Details");
        btnViewDeathGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeathGrantActionPerformed(evt);
            }
        });

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cbDeathGrantPrison.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDeathGrantPrison.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));
        cbDeathGrantPrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeathGrantPrisonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Prison");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Emp No");

        txtEmpNo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpNo2KeyTyped(evt);
            }
        });

        btnSearch4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch4.setText("Search");
        btnSearch4.setToolTipText("Click here to search member");
        btnSearch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cbDeathGrantPrison, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch4)
                            .addComponent(txtEmpNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDeathGrantPrison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSearch4))
        );

        jScrollPane5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblDeathGrant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDeathGrant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DeathGrant No", "Last Name", "Emp NIC", "Prison", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblDeathGrant);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewDeathGrant, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnViewDeathGrant)
                .addGap(29, 29, 29)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(174, 174, 174))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Death Grant Account", jPanel10);

        btnViewDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cbPrison1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPrison1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));
        cbPrison1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrison1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Prison");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Emp No");

        txtEmpNo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmpNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpNo1KeyTyped(evt);
            }
        });

        btnSearch3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch3.setText("Search");
        btnSearch3.setToolTipText("Click here to search member");
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cbPrison1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch3)
                            .addComponent(txtEmpNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrison1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch3))
        );

        jScrollPane7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblScholorship.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblScholorship.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Scholorship No", "Last Name", "Emp NIC", "Prison", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblScholorship);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Scholorship Account", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1306, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Account", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnViewMember.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnViewMember.setText("View Member");
        btnViewMember.setToolTipText("Select a member in the table and click this button to view member details");
        btnViewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMemberActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Prison");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NIC");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Emp No");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNICMouseExited(evt);
            }
        });
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNICKeyTyped(evt);
            }
        });

        txtEmpNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmpNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpNoKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Click here to search member");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbPrison.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPrison.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambepussa", "Anuradhapura", "Badulla", "Batticaloa", "Bogambara(Dumbara)", "Boosa", "Dalupotha", "Galle", "Hangilipola", "Jaffna", "Kadurugasaara", "Kalutara", "Kandewatta", "Kegalle", "Kuruwita", "Mahara", "Meethirigala", "Monaragala", "Negambo", "Pallekele", "Polonnaruwa", "Taldena", "Tangalla", "Trincomalee", "Variyapola", "Vavuniya", "Watareka", "Weerawila", "Welikada" }));

        cbNIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbNIC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "X" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbPrison, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbNIC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPrison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addContainerGap())
        );

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMember);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewMember)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnViewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Member", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Report", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Settings");

        menuItemLogout.setText("Log Out");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemLogout);

        menuProfileSettings.setText("Profile Settings");

        menuViewDetails.setText("View Details");
        menuViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewDetailsActionPerformed(evt);
            }
        });
        menuProfileSettings.add(menuViewDetails);

        menuChangePassword.setText("Change PassWord");
        menuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePasswordActionPerformed(evt);
            }
        });
        menuProfileSettings.add(menuChangePassword);

        jMenu2.add(menuProfileSettings);
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Are you sure, do you want to logout ?", "Logout", JOptionPane.YES_NO_OPTION);
        System.out.print(result);
        if (result == 0) {
            System.exit(EXIT_ON_CLOSE);
        }

    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewDetailsActionPerformed

        UserDetails user = DBWithFinal.viewUserDetails(currentUserID);
        ViewUser viewUser = new ViewUser();
        viewUser.setFields(user);
        viewUser.setVisible(true);
    }//GEN-LAST:event_menuViewDetailsActionPerformed

    private void menuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePasswordActionPerformed
        ChangePassword passwordChanger = new ChangePassword();
        passwordChanger.setVisible(true);
    }//GEN-LAST:event_menuChangePasswordActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnViewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMemberActionPerformed
        ViewMemberDetails view = new ViewMemberDetails();
        try {
            view.setFields(members.get(tblMember.getSelectedRow()));
            view.setVisible(true);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
                }

                @Override
                public void windowClosing(WindowEvent e) {
                }

                @Override
                public void windowClosed(WindowEvent e) {
                    loadMember();
                }

                @Override
                public void windowIconified(WindowEvent e) {
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
                }

                @Override
                public void windowActivated(WindowEvent e) {
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
                }
            });
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnViewMemberActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
    }//GEN-LAST:event_txtNICKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String EmpNO = txtEmpNo.getText();
        String NIC = "";
        if (!txtNIC.getText().equals("")) {
            NIC = txtNIC.getText() + (String) cbNIC.getSelectedItem();
        }
        String Name = txtName.getText();
        String prison = (String) cbPrison.getSelectedItem();

        if (EmpNO.equals("") && NIC.equals("") && Name.equals("")) {
            members = DBWithFinal.getMemberByPrison(prison);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (EmpNO.equals("") && NIC.equals("")) {
            members = DBWithFinal.getMemberByName(Name, prison);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (EmpNO.equals("") && Name.equals("")) {
            members = DBWithFinal.getMemberByNIC(NIC, prison);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (Name.equals("") && NIC.equals("")) {
            members = DBWithFinal.getMemberByEmpNo(EmpNO, prison);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (NIC.equals("")) {
            members = DBWithFinal.getMemberByEmpNoAndName(EmpNO, prison, Name);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (EmpNO.equals("")) {
            members = DBWithFinal.getMemberByNICAndName(NIC, prison, Name);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else if (Name.equals("")) {
            members = DBWithFinal.getMemberByEmpNoAndNIC(EmpNO, prison, NIC);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        } else {
            members = DBWithFinal.getMemberByEmpNoAndNICAndName(EmpNO, prison, NIC, Name);
            Member memberList = new Member(members);
            tblMember.setModel(memberList);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtNIC.getText();
        if (in.length() > 8 || !Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();
        }
    }//GEN-LAST:event_txtNICKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtName.getText();
        if (c != ' ') {
            if (!Character.isLetter(c) || Character.isDigit(c)) {
                evt.consume();
                Toolkit tk = Toolkit.getDefaultToolkit();
                tk.beep();
            }
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtAccountUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountUserNameKeyTyped
        char c = evt.getKeyChar();
        String in = txtName.getText();
        if (c != ' ') {
            if (!Character.isLetter(c) || Character.isDigit(c)) {
                evt.consume();
                Toolkit tk = Toolkit.getDefaultToolkit();
                tk.beep();
            }
        }
    }//GEN-LAST:event_txtAccountUserNameKeyTyped

    private void txtAccountNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNICKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNICKeyReleased

    private void txtAccountNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNICKeyTyped
        char c = evt.getKeyChar();
        String in = txtAccountNIC.getText();
        if (in.length() > 8 || !Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();

        }
    }//GEN-LAST:event_txtAccountNICKeyTyped

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        String accountNo = txtAccountNo.getText();
        String NIC = "";
        if (!txtAccountNIC.getText().equals("")) {
            NIC = txtAccountNIC.getText() + (String) cbAccountNIC.getSelectedItem();
        }
        String Name = txtAccountUserName.getText().trim();
        String prison = (String) cbAccountPrison.getSelectedItem();

        if (accountNo.equals("") && NIC.equals("") && Name.equals("")) {
            savingsAccount = DBWithFinal.getAccountByPrison(prison);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (accountNo.equals("") && NIC.equals("")) {
            savingsAccount = DBWithFinal.getAccountByName(Name, prison);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (accountNo.equals("") && Name.equals("")) {
            savingsAccount = DBWithFinal.getAccountByNIC(NIC, prison);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (Name.equals("") && NIC.equals("")) {
            savingsAccount = DBWithFinal.getAccountByAccountNo(accountNo, prison);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (NIC.equals("")) {
            savingsAccount = DBWithFinal.getAccountByAccountNoAndName(accountNo, prison, Name);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (accountNo.equals("")) {
            savingsAccount = DBWithFinal.getAccountByNICAndName(NIC, prison, Name);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else if (Name.equals("")) {
            savingsAccount = DBWithFinal.getAccountByAccountNoAndNIC(accountNo, prison, NIC);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        } else {
            savingsAccount = DBWithFinal.getAccountByAccountNoAndNICAndName(accountNo, prison, NIC, Name);
            SavingsAccount accountList = new SavingsAccount(savingsAccount);
            tblSavingAccount.setModel(accountList);
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtAccountNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNoKeyTyped

    private void btnViewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAccountMouseClicked

    private void btnViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAccountActionPerformed
        ViewAccountDetails view = new ViewAccountDetails();
        try {
            view.setFields(savingsAccount.get(tblSavingAccount.getSelectedRow()));
            view.setVisible(true);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
                }

                @Override
                public void windowClosing(WindowEvent e) {
                }

                @Override
                public void windowClosed(WindowEvent e) {
                    loadAccount();
                }

                @Override
                public void windowIconified(WindowEvent e) {
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
                }

                @Override
                public void windowActivated(WindowEvent e) {
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
                }
            });
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnViewAccountActionPerformed

    private void txtAccountUserName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountUserName1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtName.getText();
        if (c != ' ') {
            if (!Character.isLetter(c) || Character.isDigit(c)) {
                evt.consume();
                Toolkit tk = Toolkit.getDefaultToolkit();
                tk.beep();
            }
        }
    }//GEN-LAST:event_txtAccountUserName1KeyTyped

    private void txtAccountNIC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNIC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNIC1ActionPerformed

    private void txtAccountNIC1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNIC1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNIC1KeyReleased

    private void txtAccountNIC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccountNIC1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtAccountNIC1.getText();
        if (in.length() > 8 || !Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();
        }
    }//GEN-LAST:event_txtAccountNIC1KeyTyped

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        String applicationNO = txtApplicationNo.getText();
        String NIC = "";
        if (!txtAccountNIC1.getText().equals("")) {
            NIC = txtAccountNIC1.getText() + (String) cbAccountNIC1.getSelectedItem();
        }
        String Name = txtAccountUserName1.getText();
        String prison = (String) cbAccountPrison1.getSelectedItem();

        if (applicationNO.equals("") && NIC.equals("") && Name.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByPrison(prison);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (applicationNO.equals("") && NIC.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByName(Name, prison);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (applicationNO.equals("") && Name.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByNIC(NIC, prison);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (Name.equals("") && NIC.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByAccountNo(applicationNO, prison);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (NIC.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByApplicationNoAndName(applicationNO, prison, Name);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (applicationNO.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByNICAndName(NIC, prison, Name);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else if (Name.equals("")) {
            loanAccount = DBWithFinal.getLoanAccountByApplicationNoAndNIC(applicationNO, prison, NIC);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        } else {
            loanAccount = DBWithFinal.getAccountByApplicationNoAndNICAndName(applicationNO, prison, NIC, Name);
            LoanAccount loanList = new LoanAccount(loanAccount);
            tblLoanAccount.setModel(loanList);
        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void txtApplicationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApplicationNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApplicationNoActionPerformed

    private void btnNewLoanAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewLoanAccount1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewLoanAccount1MouseClicked

    private void btnNewLoanAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewLoanAccount1ActionPerformed
        ViewLoanAccount view = new ViewLoanAccount();
        try {
            view.setFields(loanAccount.get(tblLoanAccount.getSelectedRow()));
            view.setVisible(true);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.addWindowListener(new WindowListener() {
                @Override
                public void windowOpened(WindowEvent e) {
                }

                @Override
                public void windowClosing(WindowEvent e) {
                }

                @Override
                public void windowClosed(WindowEvent e) {
                    //loadMember();
                }

                @Override
                public void windowIconified(WindowEvent e) {
                }

                @Override
                public void windowDeiconified(WindowEvent e) {
                }

                @Override
                public void windowActivated(WindowEvent e) {
                }

                @Override
                public void windowDeactivated(WindowEvent e) {
                }
            });
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnNewLoanAccount1ActionPerformed

    private void btnViewDeathGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeathGrantActionPerformed
        ViewDeathGrant view = new ViewDeathGrant();
        try {
            view.setdeathgrantFields(deathgrant.get(tblDeathGrant.getSelectedRow()));
            view.setVisible(true);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a member !\nPlease select a member.");
        }
    }//GEN-LAST:event_btnViewDeathGrantActionPerformed

    private void cbDeathGrantPrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeathGrantPrisonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeathGrantPrisonActionPerformed

    private void txtEmpNo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNo2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtEmpNo2.getText();
        if (!Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();

        }
    }//GEN-LAST:event_txtEmpNo2KeyTyped

    private void btnSearch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch4ActionPerformed
        String EmpNO = txtEmpNo1.getText();
        String prison = (String) cbDeathGrantPrison.getSelectedItem();

        if (EmpNO.equals("")) {
            deathgrant = DBWithFinal.getDeathGrantByPrison(prison);
            DeathGrant deathgrantList = new DeathGrant(deathgrant);
            tblDeathGrant.setModel(deathgrantList);
        } else {
            deathgrant = DBWithFinal.getDeathGrantByEmpNoAndPrison(EmpNO, prison);
            DeathGrant deathgrantList = new DeathGrant(deathgrant);
            tblDeathGrant.setModel(deathgrantList);
        }
    }//GEN-LAST:event_btnSearch4ActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        ViewScholorship viewScholorship = new ViewScholorship();
        try {
            viewScholorship.setFields(scholorship.get(tblScholorship.getSelectedRow()));
            viewScholorship.setVisible(true);
            viewScholorship.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "You have not selected a row !\nPlease select a row.");
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void cbPrison1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrison1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrison1ActionPerformed

    private void txtEmpNo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNo1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String in = txtEmpNo1.getText();
        if (!Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();

        }
    }//GEN-LAST:event_txtEmpNo1KeyTyped

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        String EmpNO = txtEmpNo1.getText();
        String prison = (String) cbPrison1.getSelectedItem();

        if (EmpNO.equals("")) {
            scholorship = DBWithFinal.getScholorshipByPrison(prison);
            Scholorship scholorshipList = new Scholorship(scholorship);
            tblScholorship.setModel(scholorshipList);
        } else {
            scholorship = DBWithFinal.getScholorshipByEmpNoAndPrison(EmpNO, prison);
            Scholorship scholorshipList = new Scholorship(scholorship);
            tblScholorship.setModel(scholorshipList);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void txtAccountNICMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountNICMouseExited
        // TODO add your handling code here:
        if (txtAccountNIC.getText().trim().length() < 9) {
            txtAccountNIC.setForeground(Color.red);
        } else if (txtAccountNIC.getText().trim().length() == 9) {
            txtAccountNIC.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtAccountNICMouseExited

    private void txtNICMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNICMouseExited
        // TODO add your handling code here:
        if (txtNIC.getText().trim().length() < 9) {
            txtNIC.setForeground(Color.red);
        } else if (txtNIC.getText().trim().length() == 9) {
            txtNIC.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNICMouseExited

    private void txtAccountNIC1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAccountNIC1MouseExited
        // TODO add your handling code here:
        if (txtAccountNIC1.getText().trim().length() < 9) {
            txtAccountNIC1.setForeground(Color.red);
        } else if (txtAccountNIC1.getText().trim().length() == 9) {
            txtAccountNIC1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtAccountNIC1MouseExited

    private void txtEmpNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpNoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        String in = txtEmpNo.getText();
        if (!Character.isDigit(c)) {
            evt.consume();
            Toolkit tk = Toolkit.getDefaultToolkit();
            tk.beep();

        }
    }//GEN-LAST:event_txtEmpNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Auditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Auditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Auditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Auditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewLoanAccount1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.JButton btnSearch4;
    private javax.swing.JButton btnViewAccount;
    private javax.swing.JButton btnViewDeathGrant;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewMember;
    private javax.swing.JComboBox cbAccountNIC;
    private javax.swing.JComboBox cbAccountNIC1;
    private javax.swing.JComboBox cbAccountPrison;
    private javax.swing.JComboBox cbAccountPrison1;
    private javax.swing.JComboBox cbDeathGrantPrison;
    private javax.swing.JComboBox cbNIC;
    private javax.swing.JComboBox cbPrison;
    private javax.swing.JComboBox cbPrison1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JMenuItem menuChangePassword;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenu menuProfileSettings;
    private javax.swing.JMenuItem menuViewDetails;
    private javax.swing.JTable tblDeathGrant;
    private javax.swing.JTable tblLoanAccount;
    private javax.swing.JTable tblMember;
    private javax.swing.JTable tblSavingAccount;
    private javax.swing.JTable tblScholorship;
    private javax.swing.JTextField txtAccountNIC;
    private javax.swing.JTextField txtAccountNIC1;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtAccountUserName;
    private javax.swing.JTextField txtAccountUserName1;
    private javax.swing.JTextField txtApplicationNo;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtEmpNo1;
    private javax.swing.JTextField txtEmpNo2;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
