/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Theme;

import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import com.jtattoo.plaf.smart.SmartLookAndFeel;
import controler.ThemeControler;
import de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Nishan Gunawardena
 */
public class SelectTheme extends javax.swing.JFrame {

    /**
     * Creates new form SelectTheme
     */
    public SelectTheme() {
        initComponents();
    }

    JFrame mainFrame = this;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        themeList = new javax.swing.JList();
        canceButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select theme");
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        themeList.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        themeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "HiFi", "Aero", "McWin", "Aluminium", "Black Star", "Standard", "Grapite", "Smart", "Event", "Bernstein" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        themeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(themeList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 260, 250);

        canceButton.setText("Cancel");
        canceButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                canceButtonItemStateChanged(evt);
            }
        });
        canceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(canceButton);
        canceButton.setBounds(160, 280, 73, 23);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel1.add(doneButton);
        doneButton.setBounds(40, 280, 70, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setTheme(int theme) throws UnsupportedLookAndFeelException, ParseException {
        if (theme == 0) {


            UIManager.setLookAndFeel(new HiFiLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);



        } else if (theme == 1) {

            UIManager.setLookAndFeel(new AeroLookAndFeel());

            SwingUtilities.updateComponentTreeUI(mainFrame);
        } else if (theme == 2) {

            UIManager.setLookAndFeel(new McWinLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);


        } else if (theme == 3) {

            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);

        }else if(theme==4){
            UIManager.setLookAndFeel(new SyntheticaBlackStarLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }else if(theme==5){
            UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }else if(theme==6){
            UIManager.setLookAndFeel(new GraphiteLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }else if(theme==7){
            UIManager.setLookAndFeel(new SmartLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }else if(theme==8){
            UIManager.setLookAndFeel(new FastLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }else if(theme==9){
            UIManager.setLookAndFeel(new BernsteinLookAndFeel());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        }
    }
    private void themeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themeListMouseClicked
        try {
            try {
                setTheme(themeList.getSelectedIndex());
            } catch (ParseException ex) {
                Logger.getLogger(Theme.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Theme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_themeListMouseClicked

    private void canceButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_canceButtonItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_canceButtonItemStateChanged

    private void canceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceButtonActionPerformed
        dispose();
    }//GEN-LAST:event_canceButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        try {
            int res = ThemeControler.updateTheme(themeList.getSelectedIndex());
            if(res==1){
                JOptionPane.showMessageDialog(this,"Theme Set Suxxcesfully");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Theme.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Theme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTheme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTheme().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList themeList;
    // End of variables declaration//GEN-END:variables
}
