/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fundadministrationsystem;

import DBoperations.DBoperationWithFinal;
import User.ChiefOfficer;
import DBoperations.DBoperations;
import User.AccountClerk;
import User.Auditor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Nishan Gunawardena
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Timer timer;
    int count;
    public final static int TWO_SECOND = 5;
    DBoperationWithFinal DBOperation = new DBoperationWithFinal();

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        jProgressBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prison Department Mutual Provident Fund");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUserName.setText("Admin");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(0, 0, 153));
        jProgressBar1.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  PRISON DEPARTMENT MUTUAL PROVIDENT FUND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(txtPassword))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    class TimerListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            count++;
            jProgressBar1.setValue(count);
            if (count == 100) {
                timer.stop();
                end();
                check();





            }

        }
    }

    public void end() {
        this.setVisible(false);
    }

    public void active() {
        timer.start();

    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        try {

            String userName = txtUserName.getText(), userType;
            EncryDecryp encrypt = new EncryDecryp();
            String Password = encrypt.encrypt(txtPassword.getText());

            boolean result = DBOperation.login(userName, Password);

            userType = DBOperation.getCurrentUserType(userName);
            if (result && userType.equals("Chief Officer")) {
                jProgressBar1.setVisible(true);
                count = -1;
                jProgressBar1.setValue(0);
                jProgressBar1.setStringPainted(true);
                timer = new Timer(TWO_SECOND, new TimerListener());
                active();



            } else if (result && userType.equals("Account Clerk")) {
                jProgressBar1.setVisible(true);
                count = -1;
                jProgressBar1.setValue(0);
                jProgressBar1.setStringPainted(true);
                timer = new Timer(TWO_SECOND, new TimerListener());
                active();


            } else if (result && userType.equals("Auditor")) {
                jProgressBar1.setVisible(true);
                count = -1;
                jProgressBar1.setValue(0);
                jProgressBar1.setStringPainted(true);
                timer = new Timer(TWO_SECOND, new TimerListener());
                active();

            } else {
                JOptionPane.showMessageDialog(this, "Login Not sucessful !");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Login Not sucessful !");
        }





    }//GEN-LAST:event_btnLoginActionPerformed
    void check() {
        try {

            String userName = txtUserName.getText(), userType;
            EncryDecryp encrypt = new EncryDecryp();
            String Password = encrypt.encrypt(txtPassword.getText());

            boolean result = DBOperation.login(userName, Password);

            userType = DBOperation.getCurrentUserType(userName);
            if (result && userType.equals("Chief Officer")) {

                timer = new Timer(TWO_SECOND, new TimerListener());
                active();


                String UserID = DBOperation.getUserID(userName);

                String CurrentuserName = DBOperation.getUserName(UserID);


                ChiefOfficer chiefOfficer = new ChiefOfficer(UserID);


                chiefOfficer.setVisible(true);
                //Load the Current users name to the window
                chiefOfficer.txtUserName.setText(" " + CurrentuserName);
                setVisible(false);


            } else if (result && userType.equals("Account Clerk")) {
                String UserID = DBOperation.getUserID(userName);
                String CurrentuserName = DBOperation.getUserName(UserID);

                this.dispose();
                AccountClerk accountClerk = new AccountClerk(UserID);

                accountClerk.setVisible(true);
                //Load the Current users name to the window
                accountClerk.txtUserName.setText(CurrentuserName);


            } else if (result && userType.equals("Auditor")) {
                String UserID = DBOperation.getUserID(userName);
                String CurrentuserName = DBOperation.getUserName(UserID);

                this.dispose();
                Auditor auditor = new Auditor(UserID);

                auditor.setVisible(true);
                //Load the Current users name to the window
                auditor.txtUserName.setText(CurrentuserName);

            } else {
                JOptionPane.showMessageDialog(this, "Login Not sucessful !");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Login Not sucessful !");
        }





    }
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped

        if ('\n' == evt.getKeyChar()) {
            try {
                String userName = txtUserName.getText(), userType;
                EncryDecryp encrypt = new EncryDecryp();
                String Password = encrypt.encrypt(txtPassword.getText());

                boolean result = DBOperation.login(userName, Password);

                userType = DBOperation.getCurrentUserType(userName);
                //System.out.println("HI");
                if (result && userType.equals("Chief Officer")) {
                    jProgressBar1.setVisible(true);
                    count = -1;
                    jProgressBar1.setValue(0);
                    jProgressBar1.setStringPainted(true);
                    timer = new Timer(TWO_SECOND, new TimerListener());
                    active();
                } else if (result && userType.equals("Account Clerk")) {
                    jProgressBar1.setVisible(true);
                    count = -1;
                    jProgressBar1.setValue(0);
                    jProgressBar1.setStringPainted(true);
                    timer = new Timer(TWO_SECOND, new TimerListener());
                    active();


                } else if (result && userType.equals("Auditor")) {
                    jProgressBar1.setVisible(true);
                    count = -1;
                    jProgressBar1.setValue(0);
                    jProgressBar1.setStringPainted(true);
                    timer = new Timer(TWO_SECOND, new TimerListener());
                    active();
                } else {
                    JOptionPane.showMessageDialog(this, "Login Not sucessful !");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Login Not sucessful !");
            }


        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
           char c = evt.getKeyChar();
        String in = txtUserName.getText();
        if (c != ' ') {
            if (!Character.isLetter(c)) {
                evt.consume();
                Toolkit tk = Toolkit.getDefaultToolkit();
                tk.beep();
            }}
        
        
    }//GEN-LAST:event_txtUserNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
